### ISSUE TITLE
Add filtering to GraphQL queries.

### ISSUE THREAD

**Issue by denvash** [social-gissy-network/core#8]
As we write our own queries, we need to add the default functionalities of Graphql queries like `filter`, `limit` and `sort.

Example of a **valid query**.

```graphql
{
  allSite(filter: {}, limit: 10, sort: {fields: id, order: ASC}) {
    distinct(field: id)
  }
}
```

Desired functionality example (**Not sure** 100% that it is a valid query):

```graphql
{
  Edge {
    startNode(sort: {fields: latitude, order: ASC}) {
      id
      latitude
    }
  }
}
```

> Note: Currently **we don't need a specific** query, just the functionality.

**Comment by Jenyapa** [comment]
sort & filter implemented and deployed to prod.

A sample query can be:
`query {
  Edges (
    filter: {startNode: {id: {contains: "2"}} startTime: {lt: "2019-10-04", gt: "2019-10-03 23:00"}}
    sort: {bikeID: ASC, startTime: DESC}
  ) {
   id bikeID startTime startNode { id }
  }
}`

Which returns the all edges between start time 2019-10-03 23:00 and 2019-10-03 23:59, which started from node that contains "2" on node.id, sort by bikeID and in case of equality between bikeID's - will be sorted by startTime.

As far as I concert, there is no need of "LIMIT". If the response size is too big for the client, consider EventSource: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events OR getting the response in chucks: https://stackoverflow.com/questions/5083914/get-the-whole-response-body-when-the-response-is-chunked

**Comment by denvash** [comment]
I need `limit` for two reasons:

1. When developing/testing UI components I want to limit the query for not rendering everything.

2. Consider a valid query: "For current node/edge, sorted by X, show me the first N"
